### ISSUE TITLE
docker compose version

### ISSUE THREAD

**Issue by rukai** [stephanbuys/docker-compose-types#1]
Is this designed for docker compose version 2 or 3 or both?
Would be good to document this in the readme.

**Comment by rbozan** [comment]
see https://docs.rs/docker-compose-types/0.1.5/docker_compose_types/enum.ComposeFile.html#method.deserialize

**Comment by stephanbuys** [comment]
@rukai happy to include any compatibility improvements. There's a lot of unit test included, if you find that something is something or doesn't work as expected you are welcome to provide a patch or if you point out the issue I can have a look.

**Comment by rbozan** [comment]
> @rukai happy to include any compatibility improvements. There's a lot of unit test included, if you find that something is something or doesn't work as expected you are welcome to provide a patch or if you point out the issue I can have a look.

The only thing I'm wondering if it supports extensions (https://docs.docker.com/compose/compose-file/#extension), which from a quick look doesn't look like it.

**Comment by stephanbuys** [comment]
Yeah, the spec is enormous and I haven't seen those before, but I think it should be simple enough to add. Can you give me a snippet of what you would like to support?

**Comment by stephanbuys** [comment]
@rbozan I've implemented support for extensions.
