### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by jcaesar** [stephanbuys/docker-compose-types#22]
I'd be happy to see a basic "Parse a file this way" example in the README / top level crate documentation. Maybe something like

```rust
let mut def = serde_yaml::from_slice::<YamlValue>(read("./docker-compose.yml")?.as_slice())?;
def.apply_merge()?;
let def = serde_yaml::from_value::<ComposeFile>(def)?;
```

(There doesn't happen to be a way to handle env expansion that I missed?)

**Comment by jcaesar** [comment]
Hm. Looking at [haddock](https://github.com/seowalex/haddock/blob/master/src/compose.rs#L85), variable interpolation is somewhat complex (there's a nom parser behind this).

**Comment by jcaesar** [comment]
All right, since I have a concrete thing I need to implement, I'll go with
```rust
struct OsEnv;
impl compose_yml::v2::Environment for OsEnv {
    fn var(&self, key: &str) -> Result<String, VarError> {
        std::env::var(key)
    }
}

fn interpolate(v: &mut YamlValue, e: &dyn compose_yml::v2::Environment) -> Result<()> {
    match v {
        YamlValue::String(s) => {
            *s = compose_yml::v2::raw::<String, _>(s.clone())?
                .interpolate_env(e)?
                .clone();
        }
        YamlValue::Sequence(s) => {
            for s in s {
                interpolate(s, e)?;
            }
        }
        YamlValue::Mapping(m) => {
            for v in m.values_mut() {
                interpolate(v, e)?;
            }
        }
        YamlValue::Tagged(tagged) => interpolate(&mut tagged.value, e)?,
        _ => (),
    }
    Ok(())
}

interpolate(&mut def, &OsEnv)?;
```
for now and worry about a pretty PR to docker-compose-types later.

**Comment by stephanbuys** [comment]
Perfectly valid solution! Glad you managed to get something working for yourself.

**Comment by stephanbuys** [comment]
@jcaesar I'm going to close this issue for now, feel free to come by and help us improve the README if you still want to at some point in the future.
