### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by k9withabone** [stephanbuys/docker-compose-types#23]
First off, thank you for creating this crate, it has saved me a lot of work.

I did notice that some properties are missing. I used [mailcow's docker-compose.yml](https://github.com/mailcow/mailcow-dockerized/blob/master/docker-compose.yml) as a test because it's rather involved and uses some more obscure options. Here's a list of missing properties that I've found so far:

- services.service.networks.aliases
- services.service.tmpfs
- services.service.volumes.tmpfs
- services.service.sysctls
- services.service.ulimits.nproc
- services.service.security_opt
- networks.network.driver_opts
- networks.network.enable_ipv6
- networks.network.ipam.driver

I'm willing to work on adding these myself. Would you prefer several smaller pull requests or one larger one?

**Comment by stephanbuys** [comment]
Hi @k9withabone, I'm happy for any contributions, these should be simple to add, feel free to do it in one pull request. There tests are also failing (I discovered I wasn't parsing all the example files in our suite) which might add some more to your list.

**Comment by k9withabone** [comment]
I've gotten my list completed. Ended up refactoring a few things since this will be a breaking change anyway. I was wondering what your opinion is on `Option<Vec<T>>` vs `Vec<T>` for optional fields. Most of the code uses the former, but there is some mixing of the two, for example in `Service`. Personally, I prefer `Vec<T>`, but there are arguments for both. I don't mind going through the code and standardizing it either way.

**Comment by stephanbuys** [comment]
@k9withabone I think `Vec<T>` is a good solution, with the option to use `serde` to just not serialize empty vec (`#[serde(default, skip_serializing_if = "Vec::is_empty")]`). Some of the code in the project is very old, and would reflect a different level of understanding of the language and the crates that I used.

**Comment by stephanbuys** [comment]
@k9withabone I've worked with Docker Compose for many years but I don't know the exact answers above, I would refer to the spec just like you did. I copied those fixtures from the main docker project, its possible that some of them were faulty/invalid/skipped.
