### ISSUE TITLE
Support for Docker Compose Secrets?

### ISSUE THREAD

**Issue by ipsi** [stephanbuys/docker-compose-types#28]
I noticed while writing a little app for my home server setup that there's no explicit support for secrets. They are [part of the spec](https://docs.docker.com/compose/use-secrets/), with [top-level](https://docs.docker.com/compose/compose-file/09-secrets/) and [per-service](https://docs.docker.com/compose/compose-file/05-services/#secrets) attributes.

It's a giant pain adding them, so I was looking to automate it a bit, and it would great if there was some support for them.

**Comment by stephanbuys** [comment]
Merged #29
