### ISSUE TITLE
Implement (behind a feature branch) the Merge Crate

### ISSUE THREAD

**Issue by RuboGubo** [stephanbuys/docker-compose-types#30]
I need this [crate](https://docs.rs/merge/0.1.0/merge/) derive for my project, and thought I would quickly drop by to write the issue and implement it. I don't see any reason why you would not do this, as it can all be hidden behind a feature flag for the people that don't need it.

**Comment by stephanbuys** [comment]
@RuboGubo feel free to submit a PR for this.

**Comment by stephanbuys** [comment]
Closing this in the meantime, invitation to submit PR stands.
