### ISSUE TITLE
Add `userns_mode` and `cap_drop` fields to `Service`

### ISSUE THREAD

**Issue by k9withabone** [stephanbuys/docker-compose-types#32]
It was brought to my attention (k9withabone/podlet#31) by one of the users of my podlet project, that the `Service` struct is missing the `userns_mode` field. See the linked issue for documentation for the field. Looking at `Service`'s documentation just now I also noticed that the `cap_drop` field is also missing.

**Comment by stephanbuys** [comment]
@k9withabone do you want to submit a PR with the fix? I would just need some type information for those two fields to add it otherwise.

**Comment by k9withabone** [comment]
Yup, I got it.
