### ISSUE TITLE
Update derive_builder to 0.20.0

### ISSUE THREAD

**Issue by agavrilov** [stephanbuys/docker-compose-types#39]
It would be good to update derive_builder to 0.20.0.

Probably, you'll need to bump a minor version as 0.20.0 introduced one breaking change. I'm not sure if it affects 'docker-compose-types'. See [here](https://github.com/colin-kiegel/rust-derive-builder/blob/master/derive_builder/CHANGELOG.md#0200---2024-02-14)

**Comment by stephanbuys** [comment]
@agavrilov done, thanks. I've also introduced `serde_yml` behind a feature flag for a possible migration path in the future.
